version: "3.9"

services:
  ethmysql:
    image: "mysql:latest"
    environment:
      - MYSQL_ROOT_PASSWORD=12345678
    restart: always
    privileged: true
    ports:
      - "3306:3306"
    volumes:
      - /etc/localtime:/etc/localtime
      - ${BASEDIR}./database/data:/var/lib/mysql
      - ${BASEDIR}./v4/config/mysql/conf/my.cnf:/etc/my.cnf
      - ${BASEDIR}./v4/config/mysql/init:/docker-entrypoint-initdb.d/
